name: mullvad_daemon_debug
description: test case demonstrating Stream error Stream was terminated by peer (errorCode 1).
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^3.0.2
  protobuf: ^2.0.0
